version: '3'

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
      args:
        SCRAPE_URL: https://exactspace.co
    image: web-scrape-image:1   
    ports:
      - 80:5000  
    container_name: web-scrape-app-container